services:
  - type: web
    name: ogadoctor
    runtime: node
    plan: free
    autoDeploy: true
    buildCommand: npm install --include=dev && npm run build
    startCommand: node server/index.js
    healthCheckPath: /api/health
    envVars:
      - key: HUSKY
        value: 0
      - key: NODE_ENV
        value: production
